import { StyleSheet } from 'react-native';

const SOAP_ICON_SIZE = 36;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F8F8',
    paddingTop: 50,
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    paddingHorizontal: 12,
    marginBottom: 10,
  },
  headerRight: { alignItems: 'flex-end', gap: 6 },
  headerSettingsBtn: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.8)',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  headerSettingsIcon: { fontSize: 18, color: '#111827', fontWeight: '800' },
  main: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingBottom: 140,
    position: 'relative',
  },
  stats: {
    position: 'absolute',
    right: 11,
    bottom: 17,
    gap: 8,
    paddingHorizontal: 6,
    paddingVertical: 8,
    backgroundColor: '#D8B4FE',
    borderColor: '#E9D5FF',
    borderWidth: 1,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
  },
  soapGhost: {
    position: 'absolute',
    width: SOAP_ICON_SIZE,
    height: SOAP_ICON_SIZE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  soapGhostImage: {
    width: SOAP_ICON_SIZE,
    height: SOAP_ICON_SIZE,
    opacity: 0.75,
  },
  visitBannerWrap: {
    position: 'absolute',
    top: 24,
    left: 0,
    right: 0,
    alignItems: 'center',
    zIndex: 30,
    elevation: 8,
    pointerEvents: 'box-none',
  },
  visitBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    backgroundColor: 'rgba(15,23,42,0.94)',
    borderRadius: 18,
    paddingHorizontal: 18,
    paddingVertical: 12,
    marginHorizontal: 18,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.35)',
    shadowColor: '#0F172A',
    shadowOpacity: 0.25,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
  },
  visitBannerInfo: { flex: 1, minWidth: 0 },
  visitBannerTitle: { fontSize: 16, fontWeight: '800', color: '#F8FAFC' },
  visitBannerSubtitle: { fontSize: 12, color: '#CBD5F5', marginTop: 2 },
  visitBannerPreview: {
    width: 84,
    height: 84,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  visitBannerClose: {
    width: 32,
    height: 32,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(15,23,42,0.6)',
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.45)',
  },
  visitBannerCloseText: { fontSize: 18, color: '#F8FAFC', fontWeight: '800' },
  visitOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(15,23,42,0.55)',
    paddingHorizontal: 24,
  },
  visitCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    gap: 16,
    width: '100%',
    maxWidth: 360,
  },
  visitHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  visitTitle: { fontSize: 18, fontWeight: '800', color: '#0F172A' },
  visitSubtitle: { fontSize: 14, color: '#334155', marginTop: 4 },
  visitCloseBtn: {
    width: 34,
    height: 34,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1F2937',
  },
  visitCloseText: { fontSize: 18, fontWeight: '800', color: '#FFFFFF' },
  visitPreview: {
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 16,
    backgroundColor: '#F8FAFC',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
  },
  visitActionBtn: {
    backgroundColor: '#2563EB',
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
  },
  visitActionText: { fontSize: 14, fontWeight: '700', color: '#FFFFFF' },
  gameInviteBannerWrap: {
    position: 'absolute',
    bottom: 20,
    left: 0,
    right: 0,
    alignItems: 'center',
    zIndex: 35,
    pointerEvents: 'box-none',
  },
  gameInviteBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: 'rgba(15,23,42,0.92)',
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.4)',
    shadowColor: '#0F172A',
    shadowOpacity: 0.25,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
  },
  gameInviteBannerTitle: { fontSize: 14, fontWeight: '700', color: '#F8FAFC' },
  gameInviteBannerSubtitle: { fontSize: 11, color: '#CBD5F5', marginTop: 2 },
  gameInviteBannerCancel: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#F8FAFC',
  },
  gameInviteBannerCancelText: { color: '#F8FAFC', fontWeight: '700', fontSize: 12 },
  gameInviteOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(15,23,42,0.6)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    zIndex: 45,
  },
  gameInviteCard: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 20,
    gap: 14,
    shadowColor: '#000',
    shadowOpacity: 0.25,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
  },
  gameInviteTitle: { fontSize: 18, fontWeight: '800', color: '#0F172A' },
  gameInviteSubtitle: { fontSize: 13, color: '#475569' },
  gameInviteActions: { flexDirection: 'row', gap: 12 },
  gameInvitePrimaryBtn: {
    flex: 1,
    backgroundColor: '#2563EB',
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: 'center',
  },
  gameInvitePrimaryText: { color: '#FFFFFF', fontSize: 14, fontWeight: '700' },
  gameInviteSecondaryBtn: {
    flex: 1,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#CBD5F5',
    paddingVertical: 12,
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
  },
  gameInviteSecondaryText: { color: '#1F2937', fontSize: 14, fontWeight: '700' },
  ticTacToeOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(2,6,23,0.60)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    zIndex: 60,
  },
  ticTacToeCard: {
    width: '100%',
    maxWidth: 400,
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 24,
    gap: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    shadowColor: '#000',
    shadowOpacity: 0.25,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
  },
  ticTacToeHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  ticTacToeTitle: { fontSize: 20, fontWeight: '800', color: '#0F172A' },
  ticTacToeInfo: { fontSize: 14, color: '#475569' },
  ticTacToeBoard: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: '#F8FAFC',
  },
  ticTacToeCell: {
    width: '33.3333%',
    aspectRatio: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
  },
  ticTacToeCellNoRight: { borderRightWidth: 0 },
  ticTacToeCellNoBottom: { borderBottomWidth: 0 },
  ticTacToeCellDisabled: { backgroundColor: '#F1F5F9' },
  ticTacToeCellText: { fontSize: 40, fontWeight: '900', color: '#0F172A' },
  ticTacToeCellTextMine: { color: '#2563EB' },
  ticTacToeCellTextOpponent: { color: '#DC2626' },
  ticTacToeSymbolsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  ticTacToeSymbolText: { fontSize: 12, fontWeight: '700', color: '#1F2937' },
  ticTacToePrimaryBtn: {
    backgroundColor: '#2563EB',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
  },
  ticTacToePrimaryText: { color: '#FFFFFF', fontSize: 14, fontWeight: '700' },
  ticTacToeSecondaryBtn: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    paddingVertical: 12,
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
  },
  ticTacToeSecondaryText: { color: '#1F2937', fontSize: 13, fontWeight: '700' },
  ticTacToeCloseBtn: {
    width: 34,
    height: 34,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#111827',
  },
  ticTacToeCloseText: { color: '#F8FAFC', fontSize: 16, fontWeight: '800' },
});

export default styles;
